version: '3'

services:
  web:
    build: .
    command: python -m gunicorn brite_chatbot.asgi:application -k uvicorn.workers.UvicornWorker
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env