# Generated by Django 5.0.3 on 2024-04-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OpenAIFeedback",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("question", models.TextField(null=True)),
                ("generated_answer", models.TextField(null=True)),
                ("user_expected_answer", models.TextField(null=True)),
                ("dislike", models.BooleanField(default=False, null=True)),
            ],
            options={
                "verbose_name": "OpenAI Feedback",
                "verbose_name_plural": "OpenAI Feedback",
                "db_table": "openai_feedback",
            },
        ),
    ]
