# Generated by Django 5.0.3 on 2024-04-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="openaifeedback",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
